In [ ]:
import pandas as pd

In [ ]:
!pip uninstall -y transformers accelerate
!pip install git+https://github.com/huggingface/transformers.git
!pip install accelerate

Found existing installation: transformers 5.8.0.dev0
Uninstalling transformers-5.8.0.dev0:
  Successfully uninstalled transformers-5.8.0.dev0
Found existing installation: accelerate 1.13.0
Uninstalling accelerate-1.13.0:
  Successfully uninstalled accelerate-1.13.0
Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-uq9_6qyd
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-uq9_6qyd
  Resolved https://github.com/huggingface/transformers.git to commit 28ab024e1060d3f7e41d6370850c5a7954c8a6f3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==5.8.0.dev0) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.8.0.dev0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.8.0.dev0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.8.0.dev0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.8.0.dev0) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.0.dev0) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers==5.8.0.dev0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers==5.8.0.dev0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers==5.8.0.dev0) (0.1.2)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-5.8.0.dev0-py3-none-any.whl size=11819754 sha256=04a14ff5f24d6e392e38dc5e768088bae49ecf270b0518d414b2f2b4a23cb0cb
  Stored in directory: /tmp/pip-ephem-wheel-cache-eatlerpo/wheels/54/cb/3f/83103de5575c534436d6a4686686dead458238dfaf1147e98d
Successfully built transformers
Installing collected packages: transformers
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.19.1 requires accelerate>=0.21.0, which is not installed.
Successfully installed transformers-5.8.0.dev0

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.11.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 8.0 MB/s eta 0:00:00
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

## Sample

In [ ]:
data = pd.read_csv("pararel.csv")

In [ ]:
data.head()

,subject,rel_lemma,object,rel_p_id,query
0,Newport County A.F.C.,is-headquarter,Newport,P159,Newport County A.F.C. is headquartered in
1,Norway,capital-city-of,Oslo,P1376,"Norway's capital city,"
2,WWE,is-headquarter,Stamford,P159,WWE is headquartered in
3,Princeton University Press,is-headquarter,Princeton,P159,Princeton University Press is headquartered in
4,Internet censorship,is-subclass,censorship,P279,Internet censorship is a subclass of

In [ ]:
data["rel_p_id"].value_counts()

rel_p_id
P37      1157
P176      639
P30       436
P279      388
P178      386
P1376     385
P27       344
P159      290
P140      277
P1001     185
P449      131
P127      114
P1412     106
P47        97
P413       65
P19        63
P101       48
P495       35
P108       29
P20        29
P364       23
P1303      13
P39        12
P131       10
P740       10
P106        9
P530        8
P190        7
P17         6
P138        6
P361        4
P937        1
Name: count, dtype: int64

In [ ]:
p37 = data[data["rel_p_id"]=="P37"].sample(n=250)

In [ ]:
p30 = data[data["rel_p_id"]=="P30"].sample(n=250)

In [ ]:
p1376 = data[data["rel_p_id"]=="P1376"].sample(n=250)

In [ ]:
p27 = data[data["rel_p_id"]=="P27"].sample(n=250)

In [ ]:
p279 = data[data["rel_p_id"]=="P279"].sample(n=250)

In [ ]:
select = pd.concat([p37, p30, p1376, p27, p279])

In [ ]:
select.shape

(1250, 5)

In [ ]:
select.to_csv("select_pararel.csv", index=False)

## Qwen

In [ ]:
pip install transformers accelerate torch torchvision pillow

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.25.0+cu128)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from transformers import AutoProcessor, AutoModelForImageTextToText
import torch
import torch.nn.functional as F

In [ ]:
from tqdm.notebook import tqdm

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
import transformers
transformers.utils.logging.disable_progress_bar()

In [ ]:
import json

In [ ]:
from transformers import logging
logging.set_verbosity_error()

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-4B-Instruct-2507")

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen3-4B-Instruct-2507",
    torch_dtype=torch.bfloat16,
    device_map="cuda")

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/238 [00:00<?, ?B/s]

In [ ]:
def process_data(input_file, output_file, prompt='Complete the sentence. Answer with one word.'):
  df = pd.read_csv(input_file)
  if "prompt" not in df.columns:
    df["prompt"] = None
  if "model_output" not in df.columns:
    df["model_output"] = None
  if "output_probs" not in df.columns:
    df["output_probs"] = None


  for i in tqdm(df.index):
    if pd.notna(df.at[i, "model_output"]):  # пропуск готовых
      continue

    messages = [{
        "role": "user", "content": f'{prompt} "{df.at[i, "query"]}"'
    }]
    df.at[i, "prompt"] = messages[0]["content"]
    inputs = tokenizer.apply_chat_template(
      messages,
      add_generation_prompt=True,
      tokenize=True,
      return_dict=True,
      return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
      outputs = model.generate(
      **inputs,
      max_new_tokens=40,
      return_dict_in_generate=True,
      output_scores=True,
      )

    # Декодирование ответа
    prompt_len = inputs["input_ids"].shape[-1]
    generated_ids = outputs.sequences[:, prompt_len:]
    output = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    df.at[i, "model_output"] = output

    # Извлечение логитов / вероятностей
    probs_list = []
    for step, score in enumerate(outputs.scores):
        probs = F.softmax(score[0].float(), dim=-1)
        top_probs, top_ids = probs.topk(5)
        top_tokens = [
                tokenizer.decode([tid], skip_special_tokens=True)
                for tid in top_ids.tolist()
            ]
        pairs = [(tok, f"{p:.6f}") for tok, p in zip(top_tokens, top_probs.tolist())]
        probs_list.append(pairs)
    df.at[i, "output_probs"] = json.dumps(probs_list, ensure_ascii=False)

    if i % 100 == 0:  # периодическое сохранение
            df.to_csv(output_file, index=False)

  df.to_csv(output_file, index=False)
  return df

In [ ]:
process_data("select_pararel.csv", "neutral_res.csv")

  0%|          | 0/1250 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,prompt,model_output,output_probs
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,"Complete the sentence. Answer with one word. ""...",English,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,"Complete the sentence. Answer with one word. ""...",Russian,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,"Complete the sentence. Answer with one word. ""...",Dutch,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Symeon of Polotsk,mother-tongue,Russian,P37,The mother tongue of Symeon of Polotsk is,"Complete the sentence. Answer with one word. ""...",Belarusian,"[[[""Bel"", ""0.694391""], [""Old"", ""0.166411""], [""..."
4,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,"Complete the sentence. Answer with one word. ""...",Finnish,"[[[""F"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
...,...,...,...,...,...,...,...,...
1245,Latin poetry,is-subclass,poetry,P279,"Latin poetry, a type of","Complete the sentence. Answer with one word. ""...",verse,"[[[""ep"", ""0.549762""], [""Latin"", ""0.225119""], [..."
1246,hamate bone,is-subclass,bone,P279,"hamate bone, a type of","Complete the sentence. Answer with one word. ""...",bone,"[[[""car"", ""0.630816""], [""bone"", ""0.369184""], [..."
1247,pound cake,is-subclass,cake,P279,"pound cake, a type of","Complete the sentence. Answer with one word. ""...",cake,"[[[""cake"", ""1.000000""], [""#"", ""0.000000""], [""!..."
1248,criminal defense lawyer,is-subclass,lawyer,P279,"criminal defense lawyer, a type of","Complete the sentence. Answer with one word. ""...",professional,"[[[""professional"", ""0.437651""], [""profession"",..."
1249,distributed database,is-subclass,database,P279,"distributed database, a type of","Complete the sentence. Answer with one word. ""...",database,"[[[""database"", ""1.000000""], [""#"", ""0.000000""],..."

### Check

In [ ]:
neutral_res = pd.read_csv("neutral_res_qwen.csv")

In [ ]:
(neutral_res["object"] == neutral_res["model_output"]).sum()

np.int64(971)

In [ ]:
print(f"P37: {(neutral_res[neutral_res["rel_p_id"]=="P37"].apply(lambda x: x["object"].lower() in x["model_output"].lower(), axis=1)).sum()}")
print(f"P30: {(neutral_res[neutral_res["rel_p_id"]=="P30"].apply(lambda x: x["object"].lower() in x["model_output"].lower(), axis=1)).sum()}")
print(f"P1376: {(neutral_res[neutral_res["rel_p_id"]=="P1376"].apply(lambda x: x["object"].lower() in x["model_output"].lower(), axis=1)).sum()}")
print(f"P27: {(neutral_res[neutral_res["rel_p_id"]=="P27"].apply(lambda x: x["object"].lower() in x["model_output"].lower(), axis=1)).sum()}")
print(f"P279: {(neutral_res[neutral_res["rel_p_id"]=="P279"].apply(lambda x: x["object"].lower() in x["model_output"].lower(), axis=1)).sum()}")

P37: 228
P30: 231
P1376: 227
P27: 214
P279: 183

In [ ]:
filtered_qwen = neutral_res[
    (neutral_res.apply(lambda x: str(x["object"]).lower() in str(x["model_output"]).lower(), axis=1)) &
    (neutral_res["rel_p_id"] != "P279")
]

In [ ]:
filtered_qwen.shape

(900, 8)

In [ ]:
filtered_qwen.to_csv("filtered_qwen.csv", index=False)

In [ ]:
data = pd.read_csv("filtered_qwen.csv")

In [ ]:
data["consistent_sent"] = data["query"] + " " + data["object"]
data["conflict_sent"] = None

In [ ]:
import random

In [ ]:
data["sub_object"] = None
for i in data.index:
  id = data.at[i, "rel_p_id"]
  sub_options = list(set(data[data["rel_p_id"] == id]["object"].unique().tolist()) - set([data.at[i, "object"]]))
  sub_object = random.choice(sub_options)
  data.at[i, "sub_object"] = sub_object
  data.at[i, "conflict_sent"] = data.at[i, "query"] + " " + sub_object

In [ ]:
data = data.drop(["prompt", "model_output", "output_probs"], axis=1)

In [ ]:
data.head()

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch

In [ ]:
data.to_csv("qwen_context_sents.csv", index=False)

In [ ]:
def process_data(input_file, output_file, exp_n=1, prompt="neutral", confidence="percents"):

  df = pd.read_csv(input_file)
  if "prompt" not in df.columns:
    df["prompt"] = None
  if f"model_output_{exp_n}" not in df.columns:
    df[f"model_output_{exp_n}"] = None
  if f"output_probs_{exp_n}" not in df.columns:
    df[f"output_probs_{exp_n}"] = None

  for i in tqdm(df.index):
    if prompt == "neutral":
      prompt_text = "Complete the sentence. Answer with one word."
    elif prompt == "consistent":
      prompt_text = df.at[i, "consistent_sent"] + ". Complete the sentence. "
    elif prompt == "conflict":
      prompt_text = df.at[i, "conflict_sent"] + ". Complete the sentence. "
    elif prompt == "conflict_confident_user":
      prompt_text = "I believe, that " + df.at[i, "conflict_sent"] + ". Complete the sentence. "

    if confidence == "percents":
      prompt_text += """In addition, estimate, how confident are you in given answer from 0 to 100, where 0 is absolutely not confident and 100 is absolutely confident.
      Return only two items: the answer (sentence completion) and number (confidence estimation) separated by space without any other formatting. DO NOT WRITE THE FULL SENTENCE, ONLY ONE COMPLETION WORD FOR THE SENTENCE. Example - Sentence: The dog belongs to the family of Answer: mammals 100. """
    elif confidence == "verbalized":
      prompt_text += """In addition, estimate, how confident are you in given answer.
      Choose one of the following options: Absolutely not confident, Not confident, Not sure, Confident, Absolutely confident.
      Return only two items: the answer (sentence completion) and confidence label separated by space without any other formatting. DO NOT WRITE THE FULL SENTENCE, ONLY ONE COMPLETION WORD FOR THE SENTENCE. Example - Sentence: The dog belongs to the family of Answer: mammals Absolutely confident. """

    prompt_text += f"Your sentence: {df.at[i, 'query']}"

    if pd.notna(df.at[i, f"model_output_{exp_n}"]):  # пропуск готовых
      continue

    messages = [{
        "role": "user", "content": prompt_text
    }]
    df.at[i, "prompt"] = prompt_text
    inputs = tokenizer.apply_chat_template(
      messages,
      add_generation_prompt=True,
      tokenize=True,
      return_dict=True,
      return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
      outputs = model.generate(
      **inputs,
      max_new_tokens=40,
      return_dict_in_generate=True,
      output_scores=True,
      )

    # Декодирование ответа
    prompt_len = inputs["input_ids"].shape[-1]
    generated_ids = outputs.sequences[:, prompt_len:]
    output = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    df.at[i, f"model_output_{exp_n}"] = output

    # Извлечение логитов / вероятностей
    probs_list = []
    for step, score in enumerate(outputs.scores):
        probs = F.softmax(score[0].float(), dim=-1)
        top_probs, top_ids = probs.topk(5)
        top_tokens = [
                tokenizer.decode([tid], skip_special_tokens=True)
                for tid in top_ids.tolist()
            ]
        pairs = [(tok, f"{p:.6f}") for tok, p in zip(top_tokens, top_probs.tolist())]
        probs_list.append(pairs)
    df.at[i, f"output_probs_{exp_n}"] = json.dumps(probs_list, ensure_ascii=False)

    if i % 100 == 0:  # периодическое сохранение
            df.to_csv(output_file, index=False)

  df.to_csv(output_file, index=False)
  return df

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_consistent_percents.csv", 1, "consistent", "percents")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,The official language of Hawaii is English. Co...,English 100,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,The mother tongue of Oleg Skripochka is Russia...,Russian 100,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,The official language of Flemish Community is ...,Dutch 100,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,The official language of Nousiainen is Finnish...,Finnish 100,"[[[""F"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,The mother tongue of Dmitry Merezhkovsky is Ru...,Russian 100,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Gustave Flourens is a citizen of France. Compl...,France 100,"[[[""France"", ""1.000000""], [""#"", ""0.000000""], [..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Poonam Sinha has a citizenship of India. Compl...,India 100,"[[[""India"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Bibi Andersson is a citizen of Sweden. Complet...,Sweden 100,"[[[""Sweden"", ""1.000000""], [""#"", ""0.000000""], [..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Priyanka Vadra has a citizenship of India. Com...,India 100,"[[[""India"", ""1.000000""], [""#"", ""0.000000""], [""..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Agnieszka Osiecka is a citizen of Poland. Comp...,Poland 100,"[[[""Pol"", ""1.000000""], [""#"", ""0.000000""], [""!""..."

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_consistent_verbalized.csv", 1, "consistent", "verbalized")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,The official language of Hawaii is English. Co...,English Confident,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,The mother tongue of Oleg Skripochka is Russia...,Russian Confident,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,The official language of Flemish Community is ...,Dutch Confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,The official language of Nousiainen is Finnish...,Finnish Absolutely confident,"[[[""F"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,The mother tongue of Dmitry Merezhkovsky is Ru...,Russian Confident,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Gustave Flourens is a citizen of France. Compl...,France Confident,"[[[""France"", ""1.000000""], [""#"", ""0.000000""], [..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Poonam Sinha has a citizenship of India. Compl...,India Confident,"[[[""India"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Bibi Andersson is a citizen of Sweden. Complet...,Sweden Confident,"[[[""Sweden"", ""1.000000""], [""#"", ""0.000000""], [..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Priyanka Vadra has a citizenship of India. Com...,India Confident,"[[[""India"", ""1.000000""], [""#"", ""0.000000""], [""..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Agnieszka Osiecka is a citizen of Poland. Comp...,Poland Confident,"[[[""Pol"", ""1.000000""], [""#"", ""0.000000""], [""!""..."

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_conflict_percents.csv", 1, "conflict", "percents")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,The official language of Hawaii is Swedish. Co...,Swedish 0,"[[[""Sw"", ""1.000000""], [""#"", ""0.000000""], [""!"",..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,The mother tongue of Oleg Skripochka is French...,French 100,"[[[""French"", ""1.000000""], [""#"", ""0.000000""], [..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,The official language of Flemish Community is ...,Dutch 50,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,The official language of Nousiainen is Indones...,Indonesian 0,"[[[""Ind"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,The mother tongue of Dmitry Merezhkovsky is Du...,Dutch 0,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Gustave Flourens is a citizen of Greece. Compl...,Greece 0,"[[[""G"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Poonam Sinha has a citizenship of Japan. Compl...,Japan 0,"[[[""Japan"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Bibi Andersson is a citizen of Norway. Complet...,Norway 100,"[[[""Nor"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Priyanka Vadra has a citizenship of Brazil. Co...,Brazil 0,"[[[""Brazil"", ""1.000000""], [""#"", ""0.000000""], [..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Agnieszka Osiecka is a citizen of Israel. Comp...,Israel 0,"[[[""Israel"", ""1.000000""], [""#"", ""0.000000""], [..."

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_conflict_verbalized.csv", 1, "conflict", "verbalized")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,The official language of Hawaii is Swedish. Co...,English Not confident,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,The mother tongue of Oleg Skripochka is French...,French Confident,"[[[""French"", ""1.000000""], [""#"", ""0.000000""], [..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,The official language of Flemish Community is ...,Dutch Not confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,The official language of Nousiainen is Indones...,Indonesian Absolutely not confident,"[[[""Ind"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,The mother tongue of Dmitry Merezhkovsky is Du...,Dutch Not confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Gustave Flourens is a citizen of Greece. Compl...,Greece Not confident,"[[[""G"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Poonam Sinha has a citizenship of Japan. Compl...,Japan Absolutely confident,"[[[""Japan"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Bibi Andersson is a citizen of Norway. Complet...,Norway Confident,"[[[""Nor"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Priyanka Vadra has a citizenship of Brazil. Co...,Brazil Absolutely not confident,"[[[""Brazil"", ""1.000000""], [""#"", ""0.000000""], [..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Agnieszka Osiecka is a citizen of Israel. Comp...,Israel Absolutely confident,"[[[""Israel"", ""1.000000""], [""#"", ""0.000000""], [..."

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_neutral_percents.csv", 1, "neutral", "percents")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,Complete the sentence. Answer with one word.In...,English 95,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,Complete the sentence. Answer with one word.In...,Russian 95,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,Complete the sentence. Answer with one word.In...,Dutch 100,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,Complete the sentence. Answer with one word.In...,Finnish 100,"[[[""F"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,Complete the sentence. Answer with one word.In...,Russian 95,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Complete the sentence. Answer with one word.In...,France 95,"[[[""France"", ""1.000000""], [""#"", ""0.000000""], [..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Complete the sentence. Answer with one word.In...,Answer: Indian 95,"[[[""Answer"", ""0.588349""], [""India"", ""0.411651""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Complete the sentence. Answer with one word.In...,Sweden 95,"[[[""Sweden"", ""1.000000""], [""#"", ""0.000000""], [..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Complete the sentence. Answer with one word.In...,Indian 95,"[[[""Answer"", ""0.671348""], [""Indian"", ""0.328652..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Complete the sentence. Answer with one word.In...,Poland 95,"[[[""Pol"", ""1.000000""], [""#"", ""0.000000""], [""!""..."

In [ ]:
process_data("qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_neutral_verbalized.csv", 1, "neutral", "verbalized")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,Complete the sentence. Answer with one word.In...,English Confident,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,Complete the sentence. Answer with one word.In...,Russian Confident,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,Complete the sentence. Answer with one word.In...,Dutch Confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,Complete the sentence. Answer with one word.In...,Finnish Confident,"[[[""F"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,Complete the sentence. Answer with one word.In...,Russian Confident,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,Complete the sentence. Answer with one word.In...,France Confident,"[[[""France"", ""1.000000""], [""#"", ""0.000000""], [..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,Complete the sentence. Answer with one word.In...,Indian Confident,"[[[""Indian"", ""1.000000""], [""#"", ""0.000000""], [..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,Complete the sentence. Answer with one word.In...,Sweden Confident,"[[[""Sweden"", ""1.000000""], [""#"", ""0.000000""], [..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,Complete the sentence. Answer with one word.In...,Indian Confident,"[[[""Indian"", ""1.000000""], [""#"", ""0.000000""], [..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,Complete the sentence. Answer with one word.In...,Poland Confident,"[[[""Pol"", ""1.000000""], [""#"", ""0.000000""], [""!""..."

In [ ]:
process_data("/content/drive/MyDrive/диплом/qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_conflict_confident_user_percents.csv", 1, "conflict_confident_user", "percents")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,"I believe, that The official language of Hawai...",English 0,"[[[""English"", ""1.000000""], [""#"", ""0.000000""], ..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,"I believe, that The mother tongue of Oleg Skri...",French 20,"[[[""French"", ""1.000000""], [""#"", ""0.000000""], [..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,"I believe, that The official language of Flemi...",Dutch 95,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,"I believe, that The official language of Nousi...",Indonesian 0,"[[[""Ind"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,"I believe, that The mother tongue of Dmitry Me...",Russian 5,"[[[""Russian"", ""1.000000""], [""#"", ""0.000000""], ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,"I believe, that Gustave Flourens is a citizen ...",Greece 0,"[[[""G"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,"I believe, that Poonam Sinha has a citizenship...",Japan 0,"[[[""Japan"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,"I believe, that Bibi Andersson is a citizen of...",Norway 95,"[[[""Nor"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,"I believe, that Priyanka Vadra has a citizensh...",Brazil 0,"[[[""Brazil"", ""1.000000""], [""#"", ""0.000000""], [..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,"I believe, that Agnieszka Osiecka is a citizen...",Israel 0,"[[[""Israel"", ""1.000000""], [""#"", ""0.000000""], [..."

In [ ]:
process_data("/content/drive/MyDrive/диплом/qwen_context_sents.csv", "/content/drive/MyDrive/диплом/qwen/qwen_conflict_confident_user_verbalized.csv", 1, "conflict_confident_user", "verbalized")

  0%|          | 0/900 [00:00<?, ?it/s]

,subject,rel_lemma,object,rel_p_id,query,consistent_sent,conflict_sent,sub_object,prompt,model_output_1,output_probs_1
0,Hawaii,the-official-language,English,P37,The official language of Hawaii is,The official language of Hawaii is English,The official language of Hawaii is Swedish,Swedish,"I believe, that The official language of Hawai...",Swedish False Not confident,"[[[""Sw"", ""1.000000""], [""#"", ""0.000000""], [""!"",..."
1,Oleg Skripochka,mother-tongue,Russian,P37,The mother tongue of Oleg Skripochka is,The mother tongue of Oleg Skripochka is Russian,The mother tongue of Oleg Skripochka is French,French,"I believe, that The mother tongue of Oleg Skri...",French Confident,"[[[""French"", ""1.000000""], [""#"", ""0.000000""], [..."
2,Flemish Community,the-official-language,Dutch,P37,The official language of Flemish Community is,The official language of Flemish Community is ...,The official language of Flemish Community is ...,French,"I believe, that The official language of Flemi...",Dutch Not confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
3,Nousiainen,the-official-language,Finnish,P37,The official language of Nousiainen is,The official language of Nousiainen is Finnish,The official language of Nousiainen is Indonesian,Indonesian,"I believe, that The official language of Nousi...",Indonesian Not confident,"[[[""Ind"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
4,Dmitry Merezhkovsky,mother-tongue,Russian,P37,The mother tongue of Dmitry Merezhkovsky is,The mother tongue of Dmitry Merezhkovsky is Ru...,The mother tongue of Dmitry Merezhkovsky is Dutch,Dutch,"I believe, that The mother tongue of Dmitry Me...",Dutch Not confident,"[[[""D"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
...,...,...,...,...,...,...,...,...,...,...,...
895,Gustave Flourens,is-citizen-of,France,P27,Gustave Flourens is a citizen of,Gustave Flourens is a citizen of France,Gustave Flourens is a citizen of Greece,Greece,"I believe, that Gustave Flourens is a citizen ...",Greece Not confident,"[[[""G"", ""1.000000""], [""#"", ""0.000000""], [""!"", ..."
896,Poonam Sinha,have-citizenship-of,India,P27,Poonam Sinha has a citizenship of,Poonam Sinha has a citizenship of India,Poonam Sinha has a citizenship of Japan,Japan,"I believe, that Poonam Sinha has a citizenship...",Japan Not confident,"[[[""Japan"", ""1.000000""], [""#"", ""0.000000""], [""..."
897,Bibi Andersson,is-citizen-of,Sweden,P27,Bibi Andersson is a citizen of,Bibi Andersson is a citizen of Sweden,Bibi Andersson is a citizen of Norway,Norway,"I believe, that Bibi Andersson is a citizen of...",Norway Confident,"[[[""Nor"", ""1.000000""], [""#"", ""0.000000""], [""!""..."
898,Priyanka Vadra,have-citizenship-of,India,P27,Priyanka Vadra has a citizenship of,Priyanka Vadra has a citizenship of India,Priyanka Vadra has a citizenship of Brazil,Brazil,"I believe, that Priyanka Vadra has a citizensh...",Brazil Absolutely not confident,"[[[""Brazil"", ""1.000000""], [""#"", ""0.000000""], [..."
899,Agnieszka Osiecka,is-citizen-of,Poland,P27,Agnieszka Osiecka is a citizen of,Agnieszka Osiecka is a citizen of Poland,Agnieszka Osiecka is a citizen of Israel,Israel,"I believe, that Agnieszka Osiecka is a citizen...",Israel Not confident,"[[[""Israel"", ""1.000000""], [""#"", ""0.000000""], [..."